name: latchatche_mobile
description: "Client mobile pour La Tchatche, une application de messagerie instantanée."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
